[package]
name = "limo"
version = "0.1.0"
authors = ["Hao Hou <ghost89413@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "*"
num_cpus = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]
